version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  jupyterlab:
    image: mk-jupyter
    container_name: mk-jupyter
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark-network

  spark-master:
    image: mk-spark-master
    container_name: mk-spark-master
    hostname: spark-master
    ports:
      - 8080:8080  # Spark Master Web UI
      - 7077:7077  # Spark Master Port
      - 8998:8998  # Livy Server Port
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark-network
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077

  spark-worker-1:
    image: mk-spark-worker
    container_name: mk-spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081  # Spark Worker Web UI
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark-network
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077

networks:
  spark-network:
    driver: bridge

